##############################################################################
#' predict_attrib_dlnm
#' This function calculates daily temperature effects and aggregate them on a
#' selected period over the year
#' @param model a object containing the fitted DLNM model
#' @param newdata a data.frame in which to look for variables with which to
#' predict
#' @param coef_sim a list contained simulated DLMN coefficients. If `NULL`
#' the function used fitted parameters.
#' @param fast an option to avoid heavy calculations.
##############################################################################
predict_attrib_dlnm <- function(model, newdata, coef_sim = NULL, fast = F)
{
  if(! is(model, "list"))
  {
    stop("model should be a list generated by fit_dlnm")
  }

  if(! is(newdata, "data.frame"))
  {
    stop("The class of 'newdata' should be 'data.frame'")
  }

  if(! all(c("datedec" , "tavg", "select_period") %in% names(newdata)))
  {
    stop("Check colnames of 'newdata' ")
  }
  if(sum(newdata$select_period) == 0){
    stop("No period is selected")
  }

  # Get the basis to predict
  bvar <- do.call(onebasis, c(list(x = newdata$tavg), model$argvar))
  cenvec <- do.call(onebasis, c(list(x = model$cen), model$argvar))
  bvarcen <- scale(bvar, center = cenvec, scale = F)

  #parameters from the model
  if(is.null(coef_sim))
  {
    coef <- model$coef
  } else
  {
    coef <- coef_sim
  }

  if(fast)
  {
    df <- newdata %>% dplyr::select(datedec, years, tavg, select_period)
  } else
  {
    if(! c("nb_deaths") %in% names(newdata))
    {
      newdata$nb_deaths <- 1
    }
    df <- newdata %>% dplyr::select(datedec, years, tavg, nb_deaths, select_period)
  }
  df <- unique(df) # remove duplicated data
  df <- df[order(df$datedec), ] # order by date
  # COMPUTE THE DAILY CONTRIBUTIONS OF ATTRIBUTABLE DEATHS
  df$wt <- bvarcen %*% coef * df$select_period
  df$ewt <- exp(df$wt) * df$select_period
  df$ewt_contr <- (1 - exp(-df$wt)) * df$select_period
  df$ewt_attrib <- (df$ewt - 1) * df$select_period

  # Aggregate over year under homogeneous number of deaths during the projection
  if(fast)
  {
    df_agg <- NULL
  } else
  {
    df_agg <- df %>%
      group_by(years) %>%
      summarise(ewt_contr_year = sum(ewt_contr * nb_deaths),
                ewt_attrib_year = sum(ewt_attrib *nb_deaths),
                nb_deaths = sum(nb_deaths))
    df_agg <- df_agg %>% mutate(attrib_frac = ewt_attrib_year / nb_deaths, contr_frac = ewt_contr_year / nb_deaths)
  }
  return(list(pred_effect= df, pred_effect_year = df_agg))
}
