##############################################################################
#' predict_attrib_dlnm
#' This function calculates daily temperature effects and aggregate them on a
#' selected period over the year
#' @param model a object containing the fitted DLNM model
#' @param newdata a data.frame in which to look for variables with which to
#' predict
#' @param fast an option to avoid heavy calculations.
##############################################################################
predict_attrib_dlnm <- function(model, newdata, coef_sim = F,  fast = F, sensi = 0)
{
  if(! is(model, "list"))
  {
    stop("model should be a list generated by fit_dlnm")
  }

  if(! is(newdata, "data.frame"))
  {
    stop("The class of 'newdata' should be 'data.frame'")
  }

  if(! all(c("datedec" , "tavg", "select_period") %in% names(newdata)))
  {
    stop("Check colnames of 'newdata' ")
  }
  if(sum(newdata$select_period) == 0){
    stop("No period is selected")
  }

  if(! c("nb_deaths") %in% names(newdata))
  {
    newdata$nb_deaths <- 1
  }

  df <- newdata %>% dplyr::select(datedec, years, tavg, nb_deaths, select_period)
  df <- unique(df) # remove duplicated data
  df <- df[order(df$datedec), ] # order by date
  # COMPUTE THE DAILY CONTRIBUTIONS OF ATTRIBUTABLE DEATHS
  cb <- crossbasis(df$tavg, lag = model$lag,
                   argvar = model$argvar, arglag = model$arglag)
  # applied range of temperature
  temperature_select <- df$tavg
  if(length(which(df$select_period == 0)) >0)
    temperature_select[df$select_period == 0] <- model$cen + sensi
  # Compute daily attributable number of deaths
  attr_comp <- attrdl(x = temperature_select, basis = cb, cases = df$nb_deaths,
               model = model$model, dir= "forw",
               cen = model$cen + sensi, tot = F,
               range = NULL, sim = coef_sim, nsim = 1)
  # Extract
  if(coef_sim)
  {
    att_af <- attr_comp$af[ ,1]
    att_an <- attr_comp$an[ ,1]
  } else
  {
    att_af <- attr_comp$af
    att_an <- attr_comp$an
  }
  att_cases <- attr_comp$cases

  # Update data frame
  df$af <- replace(att_af, is.na(att_af), 0)
  df$an <- replace(att_an, is.na(att_an), 0)
  df$cases <- replace(att_cases, is.na(att_cases), 0)

  # Aggregate over year under homogeneous number of deaths during the projection
  if(fast)
  {
    df_agg <- NULL
  } else
  {
    df_agg <- df %>%
      group_by(years) %>%
      summarise(an_sum = sum(an),
                nb_deaths = sum(nb_deaths),
                cases_sum = sum(cases))
    df_agg <- df_agg %>%
      mutate(af_year = an_sum / cases_sum,
             an_year = af_year * nb_deaths,
             ajust_factor = (1 - af_year)^(-1))
  }
  return(list(pred_effect= df, pred_effect_year = df_agg))
}
