###################################
#' excess_mort : estimate temperature-related excess mortality using a
#' fitted DLNM model.
#' @param data_hist a data.frame containing historical data with columns
#' including temperature, deaths, and age bucket.
#' @param model a list of DLNM models fitted by age group, as produced by `fit_dlnm`.
#' @param q_range a 2-dimensional vector with the thresholds related to
#' extreme hot and extreme cold temperature
#' @param nsim the number of simulations to perform for bootstrapping DLNM coefficients
#' @param parallel Type of parallelization: "no", "snow", or "multicore"
#' @param ncpus number of cores to use
#' @return A list containing:
#' \itemize{
#'   \item \code{excess_mort} raw simulation results for each day
#'   \item \code{excess_mort_year} yearly aggregated excess mortality results
#'   \item \code{avg_attrib_frac} average annual attributable fractions
#' }
#'
###################################
excess_mort_dlnm <- function(data_hist, model, q_range = NULL, nsim = 1,
                             parallel = c("no", "snow", "multicore"),
                             ncpus = 1)
{
  # Match parallelization type
  parallel <- match.arg(parallel, c("no", "snow", "multicore"))

  if (parallel == "multicore" & .Platform$OS.type == "windows")
  {
    parallel <- "snow"
    warning("As the multicore option is not supported on Windows it was replaced by snow")
  }
  if ((parallel == "snow" | parallel == "multicore") & missing(ncpus))
    stop("You have to specify the number of available processors to parallelize
         the bootstrap")

  # Check model input
  if(! is(model, "list"))
  {
    stop("model should be a list generated by fit_dlnm")
  }

  # Define default thresholds if none provided
  if(is.null(q_range))
  {
    q_range[1] <- 0
    q_range[2] <- 25
  } else
  {
    if(length(q_range) != 2) stop("q_range should be of length 2")
  }

  n <- length(model)
  age_bucket <- names(model)

  # Set seed for reproducibility
  seed <- 12345

  # loop through each age bucket and simulate excess mortality
  res <- do.call("rbind", lapply(1:n, function(x)
  {
    if(n > 1) # model per age bucket
    {
      temp_model <- model[[x]]
      dem <- data_hist %>% filter(age_bk == age_bucket[x])

      # objects in memory
      vect_import <- c("n", "x", "coef_sim", "temp_model", "dem", "q_range",
                       "dem", "fold_bib")
    } else
    {
      temp_model <- model
      # Demography
      dem <- data_hist
      # objects in memory
      vect_import <- c("n", "coef_sim", "temp_model", "dem", "q_range",
                       "dem", "fold_bib")
    }

    # Compute bootstrapped coefficients
    if (nsim == 1)
    {
      coef_sim <- FALSE
    } else
    {
      set.seed(seed + x)
      coef_sim <- TRUE
    }

    # Define temperature-related conditions
    config_temp <-list(
      all_effect = dem %>% mutate(select_period = 1),
      hot_effect = dem %>% mutate(select_period = 1 * (dem$TAVG >  temp_model$cen)),
      cold_effect = dem %>% mutate(select_period = 1 * (dem$TAVG <  temp_model$cen)),
      moderate_hot_effect = dem %>% mutate(select_period = 1 * (dem$TAVG >  temp_model$cen & dem$TAVG <  q_range[2])),
      moderate_cold_effect = dem %>% mutate(select_period = 1 * (dem$TAVG <  temp_model$cen & dem$TAVG >  q_range[1])),
      extr_hot_effect = dem %>% mutate(select_period = 1 * (dem$TAVG >  q_range[2])),
      extr_cold_effect = dem %>% mutate(select_period = 1 * (dem$TAVG <  q_range[1])),
      canicule_effect = dem %>% mutate(select_period = 1 * (dem$Ind_canicule == 1))
    )

    # Simulation function for a single run
    pred_effect_sim <- function(i)
    {
      # extract coefs and compute all temperature effects
      pred_effect <- lapply(names(config_temp), function(k)
      {
        # Merge temperature effect with original data
        df <- config_temp[[k]]
        pred <- predict_attrib_dlnm(temp_model, newdata = df, coef_sim = coef_sim)$pred_effect
        # Agregate results on the populations
        df <- df %>%
          dplyr::select(DateDec, age_bk)
        pred <- pred %>%
          left_join(y = df, by = c("DateDec")) %>%
          rename(Dxtd = Nombre_de_deces) %>%
          mutate(temp_effect = k)

        # Agregate by year to reduce size if nsim > 10
        if(nsim > 10)
        {
          pred <- pred %>%
            group_by(YEARS, age_bk, temp_effect) %>%
            summarise(
              Dxt = sum(Dxtd),
              an_sum = sum(an),
              cases_sum = sum(cases)) %>%
            mutate(af_year = an_sum / cases_sum,
                   an_year = af_year * Dxt,
                   ajust_factor = (1 - af_year)^(-1))
        }
        return(pred)
      })

      pred_effect <- do.call("rbind", pred_effect)
      pred_effect$sim <- i
      return(pred_effect)
    }


    # Run simulation with parallelization if requested
    if (parallel != "no" && nsim > 1)
    {
      if (parallel == "snow") type.par <- "PSOCK"
      else if (parallel == "multicore") type.par <- "FORK"
      if (parallel == "multicore" & .Platform$OS.type == "windows")
      {
        parallel <- "snow"
        warning("As the multicore option is not supported on Windows it was replaced by snow.")
      }
      clus <- parallel::makeCluster(ncpus, type = type.par)
      parallel::clusterExport(clus, vect_import, envir=environment())
      parallel::clusterEvalQ(clus, {
        source(paste(fold_bib,"predict_attrib_dlnm.R",sep=""), encoding = "UTF-8")
        source(paste(fold_bib,"utils.R",sep=""), encoding = "UTF-8")
        source(paste(fold_bib,"attrdl.R",sep=""), encoding = "UTF-8")
        invisible(lapply(c("lubridate", "splines","mgcv", "dlnm", "data.table",
                           "ggplot2","scales","readxl","kableExtra", "dplyr", "tidyr", "mvtnorm", "Rfast",
                           "parallel"), instal.import.package))
      })
      pred <- try(parallel::parLapply(clus, 1:nsim, pred_effect_sim))
      if(!inherits(pred, "try-error"))
      {
        pred <- do.call("rbind", pred)
        pred <- pred %>% relocate(sim, .before = age_bk)
      }
      parallel::stopCluster(clus)
    } else
    {
      if(nsim == 1)
      {
        pred <- data.frame(pred_effect_sim(1))
      } else
      {
        pred <- do.call("rbind",lapply(X = 1:nsim, FUN = pred_effect_sim))
        pred <- pred %>% relocate(sim, .before = age_bk)
      }
    }
    return(pred)
  }))


  # Summarize results
  if(nsim > 10){
    # res_agg and res are equal because we do not calculate the number of death
    # for each day is nsim >10
    res_agg = NULL
    res_mean = NULL
  } else {
    res_agg <- res %>%
      group_by(YEARS, age_bk, temp_effect, sim) %>%
      summarise(Dxt = sum(Dxtd),
                an_sum = sum(an),
                cases_sum = sum(cases)) %>%
      mutate(af_year = an_sum / cases_sum,
             an_year = af_year * Dxt,
             ajust_factor = (1 - af_year)^(-1))
    # Aggregate age bk and temp_effect
    res_mean <- res %>%
      na.omit() %>%
      group_by(age_bk, temp_effect, sim) %>%
      summarise(Dxt = mean(Dxtd),
                an_sum = sum(an),
                cases_sum = sum(cases)) %>%
      mutate(af_mean = an_sum / cases_sum,
             an_mean = af_mean * Dxt,
             ajust_factor = (1 - af_mean)^(-1))
  }

  return(list(excess_mort = res,
              excess_mort_year = res_agg,
              avg_attrib_frac = res_mean))
}

