###################################
#' perf_dnlm: evaluate the performance of a fitted DLNM
#' by comparing observed and predicted mortality across age buckets and time.
#'
#' @param model A list object created by `fit_dlnm()` containing one or more
#' fitted DLNM models, each associated with a specific age group.
#'
#' @return A list containing:
#'   - perf: ggplot object (violin plot of observed vs. predicted deaths)
#'   - desc_1: ggplot object (observed vs. predicted deaths over time)
#'   - desc_2: ggplot object (attributable vs. non-attributable predicted deaths)
#'   - residual: ggplot object (diagnostic plot of deviance residuals)
#'   - res_agg: aggregated daily results by date and age group
#'   - res_agg_year: yearly aggregated results
#'   - res_mean: total aggregated results per age group
#'   - table_res_mean: formatted summary table
###################################

perf_dnlm <- function(model)
{

  # Check that input is a list
  if(! is(model, "list"))
  {
    stop("model should be a list generated by fit_dlnm")
  }

  n <- length(model)
  age_bucket <- names(model)

  # Loop through each age bucket and compute predictions
  res <- do.call("rbind", lapply(1:n, function(x)
  {
    if(n > 1) # model per age bucket
    {
      temp_model <- model[[x]]
      # Select ages included into the bucket
      dem <- temp_model$model$data # demographic data

    } else
    {
      temp_model <- model
      # Demography
      dem <- temp_model$model$data
    }

    # Estimate attributable deaths using attrdl(), see  http://www.biomedcentral.com/1471-2288/14/55
    newdata  <- dem
    cb <- crossbasis(dem$TAVG, lag = temp_model$lag,
                     argvar = temp_model$argvar, arglag = temp_model$arglag)

    an <- attrdl(x = dem$TAVG,
                 basis = cb,
                 cases = newdata$Nombre_de_deces,
                 model = temp_model$model,
                 dir="forw",
                 cen=temp_model$cen, tot = F
    )$an

    # Construct daily prediction dataset with residuals and observed deaths
    temp <- dem %>%
      mutate(DateDec = dem$DateDec,
             YEARS = year(DateDec),
             pred = predict.glm(temp_model$model,newdata, "response"),
             Dxtd_xs = an) %>%
      mutate(dev.residual = residuals(temp_model$model, type ="deviance")) %>% # add residuals
      drop_na() %>% # Remove not predicted value due to the lag
      dplyr::select(YEARS, DateDec, age_bk, Nombre_de_deces, pred, dev.residual, Dxtd_xs) %>%
      rename(Dxtd = Nombre_de_deces,
             Dxtd_pred = pred)
    return(temp)
  }))

  # Daily aggregation by date and age group
  res_agg <- res %>%
    group_by(DateDec, age_bk) %>%
    summarise(Dxtd =sum(Dxtd), Dxtd_pred = sum(Dxtd_pred), Dxtd_xs = sum(Dxtd_xs)) %>%
    mutate(year = year(DateDec))

  # Yearly aggregation by age group
  res_agg_year <- res %>%
    group_by(YEARS, age_bk) %>%
    summarise(Dxt = sum(Dxtd), Dxt_pred = sum(Dxtd_pred), Dxt_xs = sum(Dxtd_xs)) %>%
    mutate(attrib_frac = Dxt_xs / Dxt)

  # Total average performance by age group
  res_mean <- res_agg_year %>%
    na.omit() %>%
    group_by(age_bk) %>%
    summarise(Dxt = sum(Dxt), Dxt_pred = sum(Dxt_pred), Dxt_xs = sum(Dxt_xs)) %>%
    mutate(attrib_frac = Dxt_xs / Dxt)

  # Format table of average performance
  table_res_mean <- kableExtra::kable(res_mean, booktabs=TRUE) %>%
    kable_classic_2(full_width = F)

  # Monthly labels for violin plots
  res_agg <- res_agg %>%
    mutate(month = as.factor(month(DateDec)))

  # Add month format
  res_agg$month <- fct_recode(res_agg$month, "Jan." = "1",
                              "Feb." ="2",
                              "Mar." ="3",
                              "Apr." = "4",
                              "May" = "5",
                              "June" = "6",
                              "July" = "7",
                              "Aug." = "8",
                              "Sept." = "9",
                              "Oct." = "10",
                              "Nov." = "11",
                              "Dec." = "12")

  # Plot 1: observed vs. Predicted daily deaths
  p_desc_1 <- ggplot(res) +
    geom_point(aes(x = DateDec, y = Dxtd), size = 0.5, col = "grey") +
    geom_line(aes(x = DateDec, y = Dxtd_pred), size = 1) +
    facet_wrap(~ age_bk) +
    xlab("Year") + ylab("Number of daily deaths") +
    theme_bw() +
    theme(legend.position = "none",
          strip.background = element_rect(fill = "white", color = NA),
          strip.text = element_text(color = "black"),
          panel.border = element_rect(color = "black", fill = NA),
          text = element_text(size = 12))

  # Plot 2: predicted deaths split into attributable and non-attributable parts
  p_desc_2 <- ggplot(res) +
    geom_line(aes(x = DateDec, y = Dxtd_xs), size = 0.5, col = "red") +
    geom_line(aes(x = DateDec, y = Dxtd_pred - Dxtd_xs), size = 0.5) +
    facet_wrap(~ age_bk) +
    xlab("Year") + ylab("Predicted number of daily deaths") +
    theme_bw() +
    theme(legend.position = "none",
          strip.background = element_rect(fill = "white", color = NA),
          strip.text = element_text(color = "black"),
          panel.border = element_rect(color = "black", fill = NA),
          text = element_text(size = 12))

  # Plot 3: violin plots of observed vs. predicted deaths by month and year group
  p_perf <- res_agg %>%
    #create year buckets
    mutate(year_bk = cut(year, year_breaks, year_labels, include.lowest = T)) %>%
    group_by(year_bk, month) %>%
    ggplot() +
    geom_violin(aes(x = month, y = Dxtd , fill = "Observed"), alpha = 0.5, trim = FALSE) +
    geom_violin(aes(x = month, y = Dxtd_pred, fill = "Predicted"), alpha = 0.5, trim = FALSE) +
    facet_wrap(~ year_bk, scales = "free_x", ncol = 2) +
    xlab("Months") + ylab("Number of daily deaths") +
    scale_fill_manual(values = c("blue", "green")) +
    theme_bw() +
    theme(legend.position = "none",
          strip.background = element_rect(fill = "white", color = NA),
          strip.text = element_text(color = "black"),
          panel.border = element_rect(color = "black", fill = NA),
          text = element_text(size = 12))

  # Plot 4: deviance residuals over time
  p_resid <- ggplot(data = res) +
    geom_point(aes(x = DateDec, y =  dev.residual), size = 0.5, col = "grey",) +
    geom_smooth(aes(x = DateDec, y =  dev.residual),  size = 1) +
    facet_wrap(~ age_bk) +
    xlab("Year") + ylab("Deviance residuals") +
    geom_hline(yintercept= -2, linetype="dashed", color = "black") +
    geom_hline(yintercept= 2, linetype="dashed", color = "black") +
    geom_hline(yintercept= 0, color = "black") +
    theme_bw() +
    theme(legend.position = "none",
          strip.background = element_rect(fill = "white", color = NA),
          strip.text = element_text(color = "black"),
          panel.border = element_rect(color = "black", fill = NA),
          text = element_text(size = 12))

  # Return a list of all outputs
  return(list(perf = p_perf,
              desc_1 = p_desc_1,
              desc_2 = p_desc_2,
              residual = p_resid,
              res_agg = res_agg,
              res_agg_year = res_agg_year,
              res_mean = res_mean,
              table_res_mean = table_res_mean
  ))
}
